"""Fase 9 — Composizione del dossier in Markdown.

Deterministico al 100%: template fisso, bibliografia costruita dai metadati reali.
La lingua (`it`/`en`) è solo di facciata: la letteratura resta in gran parte inglese,
qui traduciamo titolo, indice, intestazioni di sezione ed etichette di contorno.
"""
from __future__ import annotations

import re
from typing import Dict, List

from .models import Author, Dossier, Paper

# Etichette bilingue del report. Le voci `sec_*` sono usate SIA come titolo di sezione
# SIA per generare l'ancora dell'indice, così le due cose non possono divergere.
LABELS: Dict[str, Dict[str, str]] = {
    "it": {
        "report_title": "Dossier di letteratura",
        "generated_by": "Generato da Musa il",
        "session": "sessione",
        "model": "modello",
        "toc": "Indice",
        "sec_overview": "Panoramica",
        "sec_foundational": "Paper fondamentali",
        "sec_frontier": "Frontiera recente",
        "sec_authors": "Autori di riferimento",
        "sec_map": "Mappa tematica",
        "sec_gaps": "Lacune e domande aperte",
        "sec_verify": "Note di verifica",
        "sec_method": "Metodo e limiti",
        "overview_empty": "_(non disponibile)_",
        "foundational_desc": "_Alto impatto assoluto, tipicamente i classici del campo._",
        "foundational_empty": "_Nessun paper classificato come fondamentale._",
        "frontier_desc": "_Lavori recenti ad alto impatto normalizzato: dove si muove il campo ora._",
        "frontier_empty": "_Nessun paper recente in evidenza._",
        "authors_empty": "_Nessun autore aggregato._",
        "cluster_no_summary": "_(nessuna sintesi)_",
        "map_empty": "_Nessun cluster tematico prodotto._",
        "key_findings": "Cosa si sa (punti chiave)",
        "gaps_empty": "_Nessuna lacuna esplicita individuata._",
        "verify_empty": "_Verifica non eseguita._",
        "papers_ref": "Paper",
        "queries_used": "Termini di ricerca usati",
        "ranking_crit": "Criterio di ranking",
        "stats": "Statistiche",
        "stats_body": ("{n_papers} paper analizzati, {n_authors} autori, "
                       "{iterations} iterazioni di sintesi, tempo {elapsed}s."),
        "limits": "Limiti",
        "limits_body": (
            "le metriche di citazione (conteggi, FWCI, h-index) hanno bias noti "
            "(effetto Matteo, penalizzazione dei lavori recenti, differenze tra campi) e "
            "vanno lette come indizi, non come verità. La sintesi è prodotta da un modello "
            "locale sugli abstract e può contenere imprecisioni: verifica sempre le fonti "
            "primarie prima di citare."
        ),
        "citations": "citazioni",
        "link": "link",
        "papers_on_topic": "paper sul tema",
        "citations_in_set": "citazioni (nel set)",
        "recent": "recenti",
    },
    "en": {
        "report_title": "Literature dossier",
        "generated_by": "Generated by Musa on",
        "session": "session",
        "model": "model",
        "toc": "Table of contents",
        "sec_overview": "Overview",
        "sec_foundational": "Foundational papers",
        "sec_frontier": "Recent frontier",
        "sec_authors": "Reference authors",
        "sec_map": "Thematic map",
        "sec_gaps": "Gaps and open questions",
        "sec_verify": "Verification notes",
        "sec_method": "Method and limits",
        "overview_empty": "_(not available)_",
        "foundational_desc": "_High absolute impact, typically the classics of the field._",
        "foundational_empty": "_No paper classified as foundational._",
        "frontier_desc": "_Recent work with high normalized impact: where the field is moving now._",
        "frontier_empty": "_No recent paper stands out._",
        "authors_empty": "_No aggregated authors._",
        "cluster_no_summary": "_(no summary)_",
        "map_empty": "_No thematic cluster produced._",
        "key_findings": "What is known (key points)",
        "gaps_empty": "_No explicit gap identified._",
        "verify_empty": "_Verification not run._",
        "papers_ref": "Papers",
        "queries_used": "Search terms used",
        "ranking_crit": "Ranking criterion",
        "stats": "Statistics",
        "stats_body": ("{n_papers} papers analyzed, {n_authors} authors, "
                       "{iterations} synthesis iterations, {elapsed}s elapsed."),
        "limits": "Limits",
        "limits_body": (
            "citation metrics (counts, FWCI, h-index) have known biases (Matthew effect, "
            "penalization of recent work, cross-field differences) and should be read as "
            "hints, not as truth. The synthesis is produced by a local model over abstracts "
            "and may contain inaccuracies: always check the primary sources before citing."
        ),
        "citations": "citations",
        "link": "link",
        "papers_on_topic": "papers on topic",
        "citations_in_set": "citations (in set)",
        "recent": "recent",
    },
}


def _labels(language: str) -> Dict[str, str]:
    return LABELS.get(language, LABELS["it"])


def _anchor(title: str) -> str:
    """Genera l'ancora Markdown (stile GitHub) da un titolo di sezione."""
    s = title.lower()
    s = re.sub(r"[^\w\s-]", "", s)   # via la punteggiatura, tieni lettere/spazi/trattini
    s = re.sub(r"\s+", "-", s.strip())
    return s


def _paper_line(p: Paper, L: Dict[str, str]) -> str:
    authors = ", ".join(p.authors[:3])
    if len(p.authors) > 3:
        authors += " et al."
    bits = [f"**{p.title}**"]
    meta = []
    if authors:
        meta.append(authors)
    if p.year:
        meta.append(str(p.year))
    if p.venue:
        meta.append(f"*{p.venue}*")
    if meta:
        bits.append(" — " + ", ".join(meta))
    tail = [f"{L['citations']}: {p.cited_by_count}"]
    if p.fwci is not None:
        tail.append(f"FWCI: {p.fwci:.2f}")
    tail.append(f"score: {p.score:.2f}")
    link = p.open_access_url or (f"https://doi.org/{p.doi}" if p.doi else p.url)
    line = f"- {' '.join(bits)}  \n  <sub>{' · '.join(tail)}"
    if link:
        line += f" · [{L['link']}]({link})"
    line += "</sub>"
    return line


def _author_line(a: Author, rank: int, L: Dict[str, str]) -> str:
    meta = [f"{a.paper_count} {L['papers_on_topic']}",
            f"{a.total_citations} {L['citations_in_set']}"]
    if a.h_index is not None:
        meta.append(f"h-index: {a.h_index}")
    if a.recent_papers:
        meta.append(f"{a.recent_papers} {L['recent']}")
    line = f"{rank}. **{a.name}**"
    if a.institution:
        line += f" — {a.institution}"
    line += f"  \n   <sub>{' · '.join(meta)}</sub>"
    return line


def render_markdown(d: Dossier) -> str:
    L = _labels(getattr(d, "language", "it") or "it")
    lines: List[str] = []
    A = lines.append

    A(f"# {L['report_title']} — {d.topic}\n")
    A(f"*{L['generated_by']} {d.created_at} · {L['session']} `{d.session_id}` · "
      f"{L['model']} `{d.stats.get('model', '?')}`*\n")

    # Indice — le voci puntano alle ancore generate dagli stessi titoli di sezione.
    toc_sections = [
        L["sec_overview"], L["sec_foundational"], L["sec_frontier"],
        L["sec_authors"], L["sec_map"], L["sec_gaps"],
        L["sec_verify"], L["sec_method"],
    ]
    A(f"## {L['toc']}\n")
    for i, title in enumerate(toc_sections, start=1):
        A(f"{i}. [{title}](#{_anchor(title)})")
    A("")

    # Panoramica
    A(f"## {L['sec_overview']}\n")
    A(d.overview or L["overview_empty"])
    A("")

    # Fondamentali
    A(f"## {L['sec_foundational']}\n")
    A(L["foundational_desc"] + "\n")
    found = d.foundational or [p for p in d.papers if p.category == "foundational"]
    if found:
        for p in found[:15]:
            A(_paper_line(p, L))
    else:
        A(L["foundational_empty"])
    A("")

    # Frontiera
    A(f"## {L['sec_frontier']}\n")
    A(L["frontier_desc"] + "\n")
    frontier = d.frontier or [p for p in d.papers if p.category == "frontier"]
    if frontier:
        for p in frontier[:15]:
            A(_paper_line(p, L))
    else:
        A(L["frontier_empty"])
    A("")

    # Autori
    A(f"## {L['sec_authors']}\n")
    if d.authors:
        for i, a in enumerate(d.authors[:15], start=1):
            A(_author_line(a, i, L))
    else:
        A(L["authors_empty"])
    A("")

    # Mappa tematica
    A(f"## {L['sec_map']}\n")
    tmap = d.thematic_map
    if tmap.clusters:
        for c in tmap.clusters:
            A(f"### {c.name}\n")
            A(c.summary or L["cluster_no_summary"])
            if c.paper_ids:
                refs = _resolve_refs(c.paper_ids, d.papers)
                if refs:
                    A(f"\n{L['papers_ref']}: " + "; ".join(refs))
            A("")
    else:
        A(L["map_empty"] + "\n")

    if tmap.key_findings:
        A(f"### {L['key_findings']}\n")
        for k in tmap.key_findings:
            A(f"- {k}")
        A("")

    # Lacune
    A(f"## {L['sec_gaps']}\n")
    if tmap.open_gaps:
        for g in tmap.open_gaps:
            A(f"- {g}")
    else:
        A(L["gaps_empty"])
    A("")

    # Verifica
    A(f"## {L['sec_verify']}\n")
    if d.verification_notes:
        for n in d.verification_notes:
            A(f"- {n}")
    else:
        A(L["verify_empty"])
    A("")

    # Metodo
    A(f"## {L['sec_method']}\n")
    A(f"**{L['queries_used']}:** {', '.join(d.expanded_queries)}\n")
    A(f"**{L['ranking_crit']}:** {d.ranking_criteria}\n")
    A(f"**{L['stats']}:** " + L["stats_body"].format(
        n_papers=d.stats.get("n_papers", 0),
        n_authors=d.stats.get("n_authors", 0),
        iterations=d.stats.get("iterations", 0),
        elapsed=d.stats.get("elapsed_s", "?"),
    ) + "\n")
    A(f"**{L['limits']}:** " + L["limits_body"] + "\n")

    return "\n".join(lines)


def _resolve_refs(paper_ids: List[str], papers: List[Paper]) -> List[str]:
    index = {p.id: p for p in papers}
    out = []
    for pid in paper_ids[:8]:
        p = index.get(pid)
        if p:
            first = p.authors[0].split()[-1] if p.authors else "?"
            out.append(f"{first} {p.year or ''}".strip())
    return out
